[package]
name = "imprint_of_light"
version = "0.1.0"
authors = ["LukeEuler <luke16times@gmail.com>"]
edition = "2021"

[dependencies]
clap = "3.2.16"
image = "0.24.3"
pbr = "1.0.4"
rand = "0.8.5"
rayon = "1.5.3"
serde = "1.0.142"
serde_derive = "1.0.142"
serde_json = "1.0.83"
time = "0.3.12"
